[collectors]

[collectors.energy]
PATH="energy_lorawan.collectors.energy.EnergyCollector"
DATA_FORMAT = "geojson"
DATA_TYPE = "json"
SCHEDULE = "5m"

[handlers]

[handlers.energy]
PATH = "energy_lorawan.handlers.energy.EnergyHandler"
DATA_FORMAT = "geojson"
DATA_TYPE  = "json"
QUERY_PARAMETERS  = {}